/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package erp.cineaztec.vista;

import javax.swing.JOptionPane;

/**
 *
 * @author allen
 */
public class JFPrincipal extends javax.swing.JFrame {

    
    JIFGestionCines jifGestionCines= new JIFGestionCines();
    private String usuario;
    /**
     * Creates new form JFPrincipal
     */
    public JFPrincipal() {
        initComponents();
        this.setSize(800, 700);
        this.setTitle("Cines Aztec ERP");
        this.add(jdpEscritorio);
        usuario = JOptionPane.showInputDialog("Ingrese su usuario:");
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpEscritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmModulos = new javax.swing.JMenu();
        jmiGestionCines = new javax.swing.JMenuItem();
        jmiGestionEmpleados = new javax.swing.JMenuItem();
        jmiGestionProveedores = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jmiGestionPedidos = new javax.swing.JMenuItem();
        jmiGestionSesiones = new javax.swing.JMenuItem();
        jmiGestionPeliculas = new javax.swing.JMenuItem();
        jmiGestionReservas = new javax.swing.JMenuItem();
        jmiGestionSalas = new javax.swing.JMenuItem();
        jmiGestionProductos = new javax.swing.JMenuItem();
        jmiGestionButacas = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jdpEscritorioLayout = new javax.swing.GroupLayout(jdpEscritorio);
        jdpEscritorio.setLayout(jdpEscritorioLayout);
        jdpEscritorioLayout.setHorizontalGroup(
            jdpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jdpEscritorioLayout.setVerticalGroup(
            jdpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        getContentPane().add(jdpEscritorio, java.awt.BorderLayout.CENTER);

        jmModulos.setText("Modulos");

        jmiGestionCines.setText("Gestión Cines");
        jmiGestionCines.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiGestionCinesActionPerformed(evt);
            }
        });
        jmModulos.add(jmiGestionCines);

        jmiGestionEmpleados.setText("Gestión Empleados");
        jmModulos.add(jmiGestionEmpleados);

        jmiGestionProveedores.setText("Gestión Clientes");
        jmModulos.add(jmiGestionProveedores);

        jMenuItem1.setText("Gestión Proveedores");
        jmModulos.add(jMenuItem1);

        jmiGestionPedidos.setText("Gestión Pedidos");
        jmModulos.add(jmiGestionPedidos);

        jmiGestionSesiones.setText("Gestión Sesiones");
        jmModulos.add(jmiGestionSesiones);

        jmiGestionPeliculas.setText("Gestión Peliculas");
        jmModulos.add(jmiGestionPeliculas);

        jmiGestionReservas.setText("Gestión Reservas");
        jmModulos.add(jmiGestionReservas);

        jmiGestionSalas.setText("Gestión Salas");
        jmModulos.add(jmiGestionSalas);

        jmiGestionProductos.setText("Gestión Productos");
        jmModulos.add(jmiGestionProductos);

        jmiGestionButacas.setText("Gestión Butacas");
        jmModulos.add(jmiGestionButacas);

        jMenuBar1.add(jmModulos);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiGestionCinesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiGestionCinesActionPerformed
        jdpEscritorio.add(jifGestionCines);
        jifGestionCines.show();
    }//GEN-LAST:event_jmiGestionCinesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JDesktopPane jdpEscritorio;
    private javax.swing.JMenu jmModulos;
    private javax.swing.JMenuItem jmiGestionButacas;
    private javax.swing.JMenuItem jmiGestionCines;
    private javax.swing.JMenuItem jmiGestionEmpleados;
    private javax.swing.JMenuItem jmiGestionPedidos;
    private javax.swing.JMenuItem jmiGestionPeliculas;
    private javax.swing.JMenuItem jmiGestionProductos;
    private javax.swing.JMenuItem jmiGestionProveedores;
    private javax.swing.JMenuItem jmiGestionReservas;
    private javax.swing.JMenuItem jmiGestionSalas;
    private javax.swing.JMenuItem jmiGestionSesiones;
    // End of variables declaration//GEN-END:variables
}
