/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package erp.cinesaztec.vista;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;


/**
 *
 * @author allen
 */
class JFPrincipal extends javax.swing.JFrame {

    
    private JIFGestionCines jifGestionCines = new JIFGestionCines();
    private JIFGestionEmpleados jifGestionEmpleados = new JIFGestionEmpleados();
    private JIFGestionClientes jifGestionClientes = new JIFGestionClientes();
    private JIFGestionProveedores jifGestionProveedores = new JIFGestionProveedores();
    private JIFGestionPedidos jifGestionPedidos = new JIFGestionPedidos();
    private JIFGestionSesiones jifGestionSesiones = new JIFGestionSesiones();
    private JIFGestionPeliculas jifGestionPeliculas = new JIFGestionPeliculas();
    private JIFGestionReservas jifGestionReservas = new JIFGestionReservas();
    private JIFGestionSalas jifGestionSalas = new JIFGestionSalas();
    private JIFGestionProductos jifGestionProductos = new JIFGestionProductos();
    private JIFGestionButacas jifGestionButacas = new JIFGestionButacas();
    /**
     * Creates new form JFPrincipal
     */
    JFPrincipal() {
        initComponents();
        //this.setSize(800, 700);
        this.setSize(1000, 700);
        this.setTitle("Cines Aztec ERP");
        this.add(jdpEscritorio);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpEscritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmModulos = new javax.swing.JMenu();
        jmiGestionCines = new javax.swing.JMenuItem();
        jmiGestionEmpleados = new javax.swing.JMenuItem();
        jmiGestionClientes = new javax.swing.JMenuItem();
        jmiGestionProveedores = new javax.swing.JMenuItem();
        jmiGestionPedidos = new javax.swing.JMenuItem();
        jmiGestionSesiones = new javax.swing.JMenuItem();
        jmiGestionPeliculas = new javax.swing.JMenuItem();
        jmiGestionReservas = new javax.swing.JMenuItem();
        jmiGestionSalas = new javax.swing.JMenuItem();
        jmiGestionProductos = new javax.swing.JMenuItem();
        jmiGestionButacas = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jdpEscritorioLayout = new javax.swing.GroupLayout(jdpEscritorio);
        jdpEscritorio.setLayout(jdpEscritorioLayout);
        jdpEscritorioLayout.setHorizontalGroup(
            jdpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jdpEscritorioLayout.setVerticalGroup(
            jdpEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        getContentPane().add(jdpEscritorio, java.awt.BorderLayout.CENTER);

        jmModulos.setText("Modulos");

        jmiGestionCines.setText("Gestión Cines");
        jmiGestionCines.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiGestionCinesActionPerformed(evt);
            }
        });
        jmModulos.add(jmiGestionCines);

        jmiGestionEmpleados.setText("Gestión Empleados");
        jmiGestionEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiGestionEmpleadosActionPerformed(evt);
            }
        });
        jmModulos.add(jmiGestionEmpleados);

        jmiGestionClientes.setText("Gestión Clientes");
        jmiGestionClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiGestionClientesActionPerformed(evt);
            }
        });
        jmModulos.add(jmiGestionClientes);

        jmiGestionProveedores.setText("Gestión Proveedores");
        jmiGestionProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiGestionProveedoresActionPerformed(evt);
            }
        });
        jmModulos.add(jmiGestionProveedores);

        jmiGestionPedidos.setText("Gestión Pedidos");
        jmiGestionPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiGestionPedidosActionPerformed(evt);
            }
        });
        jmModulos.add(jmiGestionPedidos);

        jmiGestionSesiones.setText("Gestión Sesiones");
        jmiGestionSesiones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiGestionSesionesActionPerformed(evt);
            }
        });
        jmModulos.add(jmiGestionSesiones);

        jmiGestionPeliculas.setText("Gestión Peliculas");
        jmiGestionPeliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiGestionPeliculasActionPerformed(evt);
            }
        });
        jmModulos.add(jmiGestionPeliculas);

        jmiGestionReservas.setText("Gestión Reservas");
        jmiGestionReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiGestionReservasActionPerformed(evt);
            }
        });
        jmModulos.add(jmiGestionReservas);

        jmiGestionSalas.setText("Gestión Salas");
        jmiGestionSalas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiGestionSalasActionPerformed(evt);
            }
        });
        jmModulos.add(jmiGestionSalas);

        jmiGestionProductos.setText("Gestión Productos");
        jmiGestionProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiGestionProductosActionPerformed(evt);
            }
        });
        jmModulos.add(jmiGestionProductos);

        jmiGestionButacas.setText("Gestión Butacas");
        jmiGestionButacas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiGestionButacasActionPerformed(evt);
            }
        });
        jmModulos.add(jmiGestionButacas);

        jMenuBar1.add(jmModulos);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiGestionCinesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiGestionCinesActionPerformed
        jdpEscritorio.add(jifGestionCines);
        jifGestionCines.show();
    }//GEN-LAST:event_jmiGestionCinesActionPerformed

    private void jmiGestionEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiGestionEmpleadosActionPerformed
        jdpEscritorio.add(jifGestionEmpleados);
        jifGestionEmpleados.show();
    }//GEN-LAST:event_jmiGestionEmpleadosActionPerformed

    private void jmiGestionClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiGestionClientesActionPerformed
        jdpEscritorio.add(jifGestionClientes);
        jifGestionClientes.show();
    }//GEN-LAST:event_jmiGestionClientesActionPerformed

    private void jmiGestionProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiGestionProveedoresActionPerformed
        jdpEscritorio.add(jifGestionProveedores);
        jifGestionProveedores.show();
    }//GEN-LAST:event_jmiGestionProveedoresActionPerformed

    private void jmiGestionPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiGestionPedidosActionPerformed
        jdpEscritorio.add(jifGestionPedidos);
        jifGestionPedidos.show();
    }//GEN-LAST:event_jmiGestionPedidosActionPerformed

    private void jmiGestionSesionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiGestionSesionesActionPerformed
        jdpEscritorio.add(jifGestionSesiones);
        jifGestionSesiones.show();
    }//GEN-LAST:event_jmiGestionSesionesActionPerformed

    private void jmiGestionPeliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiGestionPeliculasActionPerformed
        jdpEscritorio.add(jifGestionPeliculas);
        jifGestionPeliculas.show();
    }//GEN-LAST:event_jmiGestionPeliculasActionPerformed

    private void jmiGestionReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiGestionReservasActionPerformed
        jdpEscritorio.add(jifGestionReservas);
        jifGestionReservas.show();
    }//GEN-LAST:event_jmiGestionReservasActionPerformed

    private void jmiGestionSalasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiGestionSalasActionPerformed
        jdpEscritorio.add(jifGestionSalas);
        jifGestionSalas.show();
    }//GEN-LAST:event_jmiGestionSalasActionPerformed

    private void jmiGestionProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiGestionProductosActionPerformed
        jdpEscritorio.add(jifGestionProductos);
        jifGestionProductos.show();
    }//GEN-LAST:event_jmiGestionProductosActionPerformed

    private void jmiGestionButacasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiGestionButacasActionPerformed
        jdpEscritorio.add(jifGestionButacas);
        jifGestionButacas.show();
    }//GEN-LAST:event_jmiGestionButacasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try{
            UIManager.setLookAndFeel("com.jtattoo.plaf.hifi.HiFiLookAndFeel");
        }catch(ClassNotFoundException ex){
        } catch (InstantiationException ex) {
           
    }   catch (IllegalAccessException ex) {
            Logger.getLogger(JFPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(JFPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JDesktopPane jdpEscritorio;
    private javax.swing.JMenu jmModulos;
    private javax.swing.JMenuItem jmiGestionButacas;
    private javax.swing.JMenuItem jmiGestionCines;
    private javax.swing.JMenuItem jmiGestionClientes;
    private javax.swing.JMenuItem jmiGestionEmpleados;
    private javax.swing.JMenuItem jmiGestionPedidos;
    private javax.swing.JMenuItem jmiGestionPeliculas;
    private javax.swing.JMenuItem jmiGestionProductos;
    private javax.swing.JMenuItem jmiGestionProveedores;
    private javax.swing.JMenuItem jmiGestionReservas;
    private javax.swing.JMenuItem jmiGestionSalas;
    private javax.swing.JMenuItem jmiGestionSesiones;
    // End of variables declaration//GEN-END:variables
}
