/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package erp.cinesaztec.vista;

import erp.cinesaztec.modelo.Pelicula;
import erp.cinesaztec.persistencia.PeliculaPersistencia;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author allen
 */
class JIFGestionPeliculas extends javax.swing.JInternalFrame {

    private PeliculaPersistencia pp = new PeliculaPersistencia();
    private ArrayList<Pelicula> alPelicula;
    private Pelicula pelicula;
    private Vector vPelicula = new Vector();
    private DefaultTableModel dtm = new DefaultTableModel(vPelicula, 0);
    private int contadorModificadosAlta = 0;

    /**
     * Creates new form JIFGestionPeliculas
     */
    public JIFGestionPeliculas() {
        initComponents();
        this.setTitle("Gestión Peliculas");
        vPelicula.add("Nombre Pelicula:");
        vPelicula.add("ID  Pelicula:");
        vPelicula.add("Duración Pelicula:");
        vPelicula.add("Edad Acceso:");
        jtaConsulta.setModel(dtm);
        this.setSize(990, 700);
        this.setResizable(false);

        jtpFondo.addChangeListener(new ChangeListener() {

            @Override
            public void stateChanged(ChangeEvent e) {
                if (e.getSource() instanceof JTabbedPane) {
                    reiniciarCamposConsulta();
//                    reiniciarCamposModificar();
//                    reiniciarCamposAlta();
//                    reiniciarCamposEliminar();
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtpFondo = new javax.swing.JTabbedPane();
        jtpConsulta = new javax.swing.JTabbedPane();
        jpConsulta = new javax.swing.JPanel();
        lbTitulo = new javax.swing.JLabel();
        jlIdConsulta = new javax.swing.JLabel();
        jtfINombreConsulta = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaConsulta = new javax.swing.JTable();
        jbAceptarConsulta = new javax.swing.JButton();
        jtpModificar = new javax.swing.JTabbedPane();
        jpModificar = new javax.swing.JPanel();
        jlNombrePelicula = new javax.swing.JLabel();
        jjIdPeliculaCine = new javax.swing.JLabel();
        jlIdBuscador = new javax.swing.JLabel();
        jlDuracionPelicula = new javax.swing.JLabel();
        jlEdad = new javax.swing.JLabel();
        jtfNombreBuscador = new javax.swing.JTextField();
        jtfNombrePeliculaModificar = new javax.swing.JTextField();
        jtfIdPeliculaModificar = new javax.swing.JTextField();
        jtfDuraciónPeliculaModificar = new javax.swing.JTextField();
        jtfEdadAccesoModificar = new javax.swing.JTextField();
        jbtModificar = new javax.swing.JButton();
        jbtBuscarPeliculaModificar = new javax.swing.JButton();
        jlNombreActual = new javax.swing.JLabel();
        jlIdActual = new javax.swing.JLabel();
        jlDuracionActual = new javax.swing.JLabel();
        jlEdadAccesoActual = new javax.swing.JLabel();
        jlNombreResultado = new javax.swing.JLabel();
        jlIdResultado = new javax.swing.JLabel();
        jlDuracionResultado = new javax.swing.JLabel();
        jlEdadAccesoResultado = new javax.swing.JLabel();
        jtpAltaCine = new javax.swing.JTabbedPane();
        jpAltaCine = new javax.swing.JPanel();
        jlNombreAlta = new javax.swing.JLabel();
        jtfNombreNuevoAltaPelicula = new javax.swing.JTextField();
        jlDuracionAlta = new javax.swing.JLabel();
        jtfDuracionNuevoAltaPelicula = new javax.swing.JTextField();
        jlEdadAcceso = new javax.swing.JLabel();
        jtfEdadAccesoNuevaAltaPelicula = new javax.swing.JTextField();
        jbAltaPelicula = new javax.swing.JButton();
        jtpEliminar = new javax.swing.JTabbedPane();
        jpFondoEliminar = new javax.swing.JPanel();
        jlNombrePeliculaEliminar = new javax.swing.JLabel();
        jtfNombrePeliculaEliminar = new javax.swing.JTextField();
        jlPeliAEliminar = new javax.swing.JLabel();
        jbAceptarIdEliminar = new javax.swing.JButton();
        jlNombrePeliculaAEliminar = new javax.swing.JLabel();
        jlDuracionPeliculaAELiminar = new javax.swing.JLabel();
        jlEdadAccesoAEliminar = new javax.swing.JLabel();
        jbConfirmarEliminar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jtpFondo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jtpFondoStateChanged(evt);
            }
        });

        jtpConsulta.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jtpConsultaStateChanged(evt);
            }
        });
        jtpConsulta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtpConsultaFocusLost(evt);
            }
        });

        lbTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitulo.setText("Ingrese el nombre de la película o pulse Aceptar para mostrar todoas:");

        jlIdConsulta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlIdConsulta.setText("Nombre:");

        jtaConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtaConsulta);

        jbAceptarConsulta.setText("Aceptar");
        jbAceptarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAceptarConsultaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpConsultaLayout = new javax.swing.GroupLayout(jpConsulta);
        jpConsulta.setLayout(jpConsultaLayout);
        jpConsultaLayout.setHorizontalGroup(
            jpConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 927, Short.MAX_VALUE)
                    .addComponent(lbTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpConsultaLayout.createSequentialGroup()
                        .addComponent(jlIdConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtfINombreConsulta))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpConsultaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbAceptarConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jpConsultaLayout.setVerticalGroup(
            jpConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jpConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlIdConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfINombreConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbAceptarConsulta)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        jtpConsulta.addTab("", jpConsulta);

        jtpFondo.addTab("Consulta", jtpConsulta);

        jlNombrePelicula.setText("Nombre:");

        jjIdPeliculaCine.setText("ID:");

        jlIdBuscador.setText("Ingrese el nombre de la película que desea modificar:");

        jlDuracionPelicula.setText("Duración:");

        jlEdad.setText("Edad Acceso:");

        jbtModificar.setText("Modificar");
        jbtModificar.setEnabled(false);
        jbtModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtModificarActionPerformed(evt);
            }
        });

        jbtBuscarPeliculaModificar.setText("Buscar");
        jbtBuscarPeliculaModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtBuscarPeliculaModificarActionPerformed(evt);
            }
        });

        jlNombreActual.setText("Nombre Actual:");

        jlIdActual.setText("ID Actual:");

        jlDuracionActual.setText("Duración:");

        jlEdadAccesoActual.setText("Edad Acceso:");

        javax.swing.GroupLayout jpModificarLayout = new javax.swing.GroupLayout(jpModificar);
        jpModificar.setLayout(jpModificarLayout);
        jpModificarLayout.setHorizontalGroup(
            jpModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpModificarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jbtModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(202, 202, 202))
            .addGroup(jpModificarLayout.createSequentialGroup()
                .addGroup(jpModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpModificarLayout.createSequentialGroup()
                        .addGroup(jpModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpModificarLayout.createSequentialGroup()
                                .addGroup(jpModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlNombrePelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jjIdPeliculaCine, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlDuracionPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(22, 22, 22))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpModificarLayout.createSequentialGroup()
                                .addComponent(jlEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(jpModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfDuraciónPeliculaModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfIdPeliculaModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfNombrePeliculaModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfEdadAccesoModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpModificarLayout.createSequentialGroup()
                        .addComponent(jlIdBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtfNombreBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtBuscarPeliculaModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpModificarLayout.createSequentialGroup()
                        .addGroup(jpModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpModificarLayout.createSequentialGroup()
                                .addComponent(jlNombreActual, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(126, 126, 126)
                                .addComponent(jlIdActual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpModificarLayout.createSequentialGroup()
                                .addComponent(jlNombreResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jlIdResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jpModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpModificarLayout.createSequentialGroup()
                                .addComponent(jlDuracionResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jlEdadAccesoResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpModificarLayout.createSequentialGroup()
                                .addComponent(jlDuracionActual, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jlEdadAccesoActual, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(176, Short.MAX_VALUE))
        );
        jpModificarLayout.setVerticalGroup(
            jpModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpModificarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlIdBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfNombreBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtBuscarPeliculaModificar))
                .addGap(18, 18, 18)
                .addGroup(jpModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNombreActual, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlIdActual, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlDuracionActual, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlEdadAccesoActual, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jpModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpModificarLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jpModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlEdadAccesoResultado, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                            .addComponent(jlDuracionResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlIdResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jpModificarLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jlNombreResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jpModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNombrePelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfNombrePeliculaModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfIdPeliculaModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jjIdPeliculaCine, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlDuracionPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfDuraciónPeliculaModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfEdadAccesoModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(jbtModificar)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jtpModificar.addTab("", jpModificar);

        jtpFondo.addTab("Modificar", jtpModificar);

        jlNombreAlta.setText("Nombre:");

        jlDuracionAlta.setText("Duración:");

        jlEdadAcceso.setText("Edad Acceso:");

        jbAltaPelicula.setText("Aceptar");
        jbAltaPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAltaPeliculaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpAltaCineLayout = new javax.swing.GroupLayout(jpAltaCine);
        jpAltaCine.setLayout(jpAltaCineLayout);
        jpAltaCineLayout.setHorizontalGroup(
            jpAltaCineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAltaCineLayout.createSequentialGroup()
                .addGroup(jpAltaCineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpAltaCineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpAltaCineLayout.createSequentialGroup()
                            .addComponent(jlNombreAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jtfNombreNuevoAltaPelicula))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpAltaCineLayout.createSequentialGroup()
                            .addComponent(jlDuracionAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jtfDuracionNuevoAltaPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpAltaCineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jbAltaPelicula)
                        .addGroup(jpAltaCineLayout.createSequentialGroup()
                            .addComponent(jlEdadAcceso, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jtfEdadAccesoNuevaAltaPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(268, Short.MAX_VALUE))
        );
        jpAltaCineLayout.setVerticalGroup(
            jpAltaCineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAltaCineLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpAltaCineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNombreAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfNombreNuevoAltaPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpAltaCineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlDuracionAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfDuracionNuevoAltaPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpAltaCineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlEdadAcceso, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfEdadAccesoNuevaAltaPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jbAltaPelicula)
                .addContainerGap(196, Short.MAX_VALUE))
        );

        jtpAltaCine.addTab("", jpAltaCine);

        jtpFondo.addTab("Alta", jtpAltaCine);

        jlNombrePeliculaEliminar.setText("Ingrese el nombre de la película que desee eliminar:");

        jlPeliAEliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlPeliAEliminar.setText("Va a eliminar la siguiente película:");

        jbAceptarIdEliminar.setText("Aceptar");
        jbAceptarIdEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAceptarIdEliminarActionPerformed(evt);
            }
        });

        jbConfirmarEliminar.setText("Eliminar");
        jbConfirmarEliminar.setEnabled(false);
        jbConfirmarEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConfirmarEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpFondoEliminarLayout = new javax.swing.GroupLayout(jpFondoEliminar);
        jpFondoEliminar.setLayout(jpFondoEliminarLayout);
        jpFondoEliminarLayout.setHorizontalGroup(
            jpFondoEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFondoEliminarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpFondoEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpFondoEliminarLayout.createSequentialGroup()
                        .addComponent(jlNombrePeliculaEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jtfNombrePeliculaEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbAceptarIdEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jlPeliAEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpFondoEliminarLayout.createSequentialGroup()
                        .addComponent(jlNombrePeliculaAEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jlDuracionPeliculaAELiminar, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jlEdadAccesoAEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(191, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpFondoEliminarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbConfirmarEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(197, 197, 197))
        );
        jpFondoEliminarLayout.setVerticalGroup(
            jpFondoEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFondoEliminarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpFondoEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpFondoEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jtfNombrePeliculaEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlNombrePeliculaEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpFondoEliminarLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jbAceptarIdEliminar)))
                .addGap(18, 18, 18)
                .addComponent(jlPeliAEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jpFondoEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlNombrePeliculaAEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(jlDuracionPeliculaAELiminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlEdadAccesoAEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jbConfirmarEliminar)
                .addContainerGap(202, Short.MAX_VALUE))
        );

        jtpEliminar.addTab("", jpFondoEliminar);

        jtpFondo.addTab("Eliminar", jtpEliminar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtpFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 957, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtpFondo)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbAceptarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAceptarConsultaActionPerformed
        consultaPelicula();
    }//GEN-LAST:event_jbAceptarConsultaActionPerformed

    private void jtpConsultaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jtpConsultaStateChanged

    }//GEN-LAST:event_jtpConsultaStateChanged

    private void jtpConsultaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtpConsultaFocusLost

    }//GEN-LAST:event_jtpConsultaFocusLost

    private void jbtModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtModificarActionPerformed
        actualizarPelicula();
    }//GEN-LAST:event_jbtModificarActionPerformed

    private void jbtBuscarPeliculaModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtBuscarPeliculaModificarActionPerformed
        MostrarPeliculaActualizar();
    }//GEN-LAST:event_jbtBuscarPeliculaModificarActionPerformed

    private void jbAltaPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAltaPeliculaActionPerformed
        ingresarPelicula();
    }//GEN-LAST:event_jbAltaPeliculaActionPerformed

    private void jbAceptarIdEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAceptarIdEliminarActionPerformed
        cargarPeliculaEliminar();
    }//GEN-LAST:event_jbAceptarIdEliminarActionPerformed

    private void jbConfirmarEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConfirmarEliminarActionPerformed
        eliminarPelicula();
    }//GEN-LAST:event_jbConfirmarEliminarActionPerformed

    private void jtpFondoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jtpFondoStateChanged

    }//GEN-LAST:event_jtpFondoStateChanged
    public void consultaPelicula() {
        String nombreBuscador = jtfINombreConsulta.getText();

        if (nombreBuscador.equals("")) {
            /* Búsqueda general de peliculas. */
            try {
                reiniciarCamposConsulta();
                alPelicula = pp.listarPelicula();
                dtm.setRowCount(alPelicula.size());
                for (int i = 0; i < alPelicula.size(); i++) {
                    jtaConsulta.setValueAt(alPelicula.get(i).getNombre_pelicula(), i, 0);
                    jtaConsulta.setValueAt(alPelicula.get(i).getId_pelicula(), i, 1);
                    jtaConsulta.setValueAt(alPelicula.get(i).getDur_pelicula(), i, 2);
                    jtaConsulta.setValueAt(alPelicula.get(i).getEdad_acceso(), i, 3);
                }
            } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(null, "Error en la aplicación.\nNo se ha podido consultar ningúna película.\nPruebe de nuevo.");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error de conexión con la BD.\nPruebe de nuevo.");
            }
        } else {
            /* Búsqueda específica de cine por CIF. */
            try {
                reiniciarCamposConsulta();
                pelicula = pp.buscarPelicula(nombreBuscador);
                dtm.setRowCount(1);
                jtaConsulta.setValueAt(pelicula.getNombre_pelicula(), 0, 0);
                jtaConsulta.setValueAt(pelicula.getId_pelicula(), 0, 1);
                jtaConsulta.setValueAt(pelicula.getDur_pelicula(), 0, 2);
                jtaConsulta.setValueAt(pelicula.getEdad_acceso(), 0, 3);

            } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(null, "Error en la aplicación.\nNo se ha podido consultar la pelicaula solicitada.\nPruebe de nuevo.");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error de conexión con la BD.\nPruebe de nuevo.");
            }
        }
    }

    public void reiniciarCamposConsulta() {
        jtfINombreConsulta.setText("");
        for (int i = 0; i < jtaConsulta.getRowCount(); i++) {
            dtm.removeRow(i);
            i -= 1;
        }
    }

    public void ingresarPelicula() {
        try {
            String nombreNuevo = jtfNombreNuevoAltaPelicula.getText();
            int duracion = Integer.parseInt(jtfDuracionNuevoAltaPelicula.getText());
            int edadAcceso = Integer.parseInt(jtfEdadAccesoNuevaAltaPelicula.getText());

            pelicula = new Pelicula(nombreNuevo, duracion, edadAcceso);
            pp.ingresarPelicula(pelicula);
            JOptionPane.showMessageDialog(null, "Pelicula ingresado con éxito.");

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error de conexión con la BD.\nNo se ha podido ingresar la nueva pelicula.\nPruebe de nuevo.");
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Error en la aplicación.\nPruebe de nuevo.");
        }
    }

    public void eliminarPelicula() {
        String nombre_pelicula_eliminar = jtfNombrePeliculaEliminar.getText();
        
        try {
            pelicula = pp.buscarPelicula(nombre_pelicula_eliminar);
            pp.eliminarPelicula(pelicula.getId_pelicula());
            JOptionPane.showMessageDialog(null, "Pelicula eliminada con éxito.");
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Error en la aplicación.\nPruebe de nuevo.");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error en la aplicación.\nNo se ha podido eliminar la pelicula solicitada.\nPruebe de nuevo.");
        }
    }

    public void cargarPeliculaEliminar() {
        String nombreBuscador = jtfNombrePeliculaEliminar.getText();

        try {
            pelicula = pp.buscarPelicula(nombreBuscador);
            jlNombrePeliculaAEliminar.setText("Nombre: " + pelicula.getNombre_pelicula());
            jlDuracionPeliculaAELiminar.setText("Duración: " + String.valueOf(pelicula.getDur_pelicula()));
            jlEdadAccesoAEliminar.setText("Edad Acceso: " + String.valueOf(pelicula.getEdad_acceso()));
            jbConfirmarEliminar.setEnabled(true);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error en la aplicación.\nNo se ha podido eliminar la pelicula solicitada.\nPruebe de nuevo.");
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Error en la aplicación.\nPruebe de nuevo.");
        }
    }

    public void MostrarPeliculaActualizar() {
        String nombreBuscador = jtfNombreBuscador.getText();
        try {
            pelicula = pp.buscarPelicula(nombreBuscador);

            jlNombreResultado.setText(pelicula.getNombre_pelicula());
            jlIdResultado.setText(String.valueOf(pelicula.getId_pelicula()));
            jlDuracionResultado.setText(String.valueOf(pelicula.getDur_pelicula()));
            jlEdadAccesoResultado.setText(String.valueOf(pelicula.getEdad_acceso()));

            jtfNombrePeliculaModificar.setText(pelicula.getNombre_pelicula());
            jtfIdPeliculaModificar.setText(String.valueOf(pelicula.getId_pelicula()));
            jtfDuraciónPeliculaModificar.setText(String.valueOf(pelicula.getDur_pelicula()));
            jtfEdadAccesoModificar.setText(String.valueOf(pelicula.getEdad_acceso()));
            jbtModificar.setEnabled(true);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error en la aplicación.\nNo se ha podido mostarar la pelicula a modificar.\nPruebe de nuevo.");
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Error en la aplicación.\nPruebe de nuevo.");
        }
    }

    public void actualizarPelicula() {

        String nombreNuevo = jtfNombrePeliculaModificar.getText();
        int duracionNueva = Integer.parseInt(jtfDuraciónPeliculaModificar.getText());
        int edadAccesoNueva = Integer.parseInt(jtfEdadAccesoModificar.getText());
        int id_pelicula = Integer.parseInt(jtfIdPeliculaModificar.getText());
        pelicula = new Pelicula(id_pelicula, nombreNuevo, duracionNueva, edadAccesoNueva);
        try {
            pp.actualizarPelicula(pelicula);
            JOptionPane.showMessageDialog(null, "Pelicula actualizada con éxito.");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error en la aplicación.\nNo se ha podido modificar la pelicula solicitada.\nPruebe de nuevo.");
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Error en la aplicación.\nPruebe de nuevo.");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAceptarConsulta;
    private javax.swing.JButton jbAceptarIdEliminar;
    private javax.swing.JButton jbAltaPelicula;
    private javax.swing.JButton jbConfirmarEliminar;
    private javax.swing.JButton jbtBuscarPeliculaModificar;
    private javax.swing.JButton jbtModificar;
    private javax.swing.JLabel jjIdPeliculaCine;
    private javax.swing.JLabel jlDuracionActual;
    private javax.swing.JLabel jlDuracionAlta;
    private javax.swing.JLabel jlDuracionPelicula;
    private javax.swing.JLabel jlDuracionPeliculaAELiminar;
    private javax.swing.JLabel jlDuracionResultado;
    private javax.swing.JLabel jlEdad;
    private javax.swing.JLabel jlEdadAcceso;
    private javax.swing.JLabel jlEdadAccesoAEliminar;
    private javax.swing.JLabel jlEdadAccesoActual;
    private javax.swing.JLabel jlEdadAccesoResultado;
    private javax.swing.JLabel jlIdActual;
    private javax.swing.JLabel jlIdBuscador;
    private javax.swing.JLabel jlIdConsulta;
    private javax.swing.JLabel jlIdResultado;
    private javax.swing.JLabel jlNombreActual;
    private javax.swing.JLabel jlNombreAlta;
    private javax.swing.JLabel jlNombrePelicula;
    private javax.swing.JLabel jlNombrePeliculaAEliminar;
    private javax.swing.JLabel jlNombrePeliculaEliminar;
    private javax.swing.JLabel jlNombreResultado;
    private javax.swing.JLabel jlPeliAEliminar;
    private javax.swing.JPanel jpAltaCine;
    private javax.swing.JPanel jpConsulta;
    private javax.swing.JPanel jpFondoEliminar;
    private javax.swing.JPanel jpModificar;
    private javax.swing.JTable jtaConsulta;
    private javax.swing.JTextField jtfDuracionNuevoAltaPelicula;
    private javax.swing.JTextField jtfDuraciónPeliculaModificar;
    private javax.swing.JTextField jtfEdadAccesoModificar;
    private javax.swing.JTextField jtfEdadAccesoNuevaAltaPelicula;
    private javax.swing.JTextField jtfINombreConsulta;
    private javax.swing.JTextField jtfIdPeliculaModificar;
    private javax.swing.JTextField jtfNombreBuscador;
    private javax.swing.JTextField jtfNombreNuevoAltaPelicula;
    private javax.swing.JTextField jtfNombrePeliculaEliminar;
    private javax.swing.JTextField jtfNombrePeliculaModificar;
    private javax.swing.JTabbedPane jtpAltaCine;
    private javax.swing.JTabbedPane jtpConsulta;
    private javax.swing.JTabbedPane jtpEliminar;
    private javax.swing.JTabbedPane jtpFondo;
    private javax.swing.JTabbedPane jtpModificar;
    private javax.swing.JLabel lbTitulo;
    // End of variables declaration//GEN-END:variables
}
