/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package erp.cinesaztec.vista;

import erp.cinesaztec.modelo.Reserva;
import erp.cinesaztec.persistencia.ReservaPersistencia;
import java.sql.SQLException;
import java.sql.Time;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author allen
 */
class JIFGestionReservas extends javax.swing.JInternalFrame {

    private ReservaPersistencia rp = new ReservaPersistencia();
    private ArrayList<Reserva> alReserva = new ArrayList();
    private Reserva reserva;
    private Vector vReserva = new Vector();
    private DefaultTableModel dtm = new DefaultTableModel(vReserva, 0);
    /**
     * Creates new form JIFGestionReservas
     */
    public JIFGestionReservas() {
        initComponents();
        vReserva.add("ID Reserva:");
        vReserva.add("Pelicula:");
        vReserva.add("Hora Sesión:");
        vReserva.add("Fila Butaca:");
        vReserva.add("Columna Butaca:");
        vReserva.add("Dni Cliente:");
        jtaConsulta.setModel(dtm);
        this.setSize(990, 700);
        this.setTitle("Gestión Reservas");
        /* Se añade un Listener para analizar cuándo se recibe algún cambio de ventana en esta ventana. */
        jtpFondo.addChangeListener(new ChangeListener() {

            @Override
            public void stateChanged(ChangeEvent e) {
                if (e.getSource() instanceof JTabbedPane) {
                    reiniciarCamposConsulta();
                    reiniciarCamposModificar();
                    reiniciarCamposAlta();
                    reiniciarCamposEliminar();
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtpFondo = new javax.swing.JTabbedPane();
        jtpConsulta = new javax.swing.JTabbedPane();
        jpConsulta = new javax.swing.JPanel();
        lbTitulo = new javax.swing.JLabel();
        jlCifConsulta = new javax.swing.JLabel();
        jtfIDConsulta = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaConsulta = new javax.swing.JTable();
        jbAceptarConsulta = new javax.swing.JButton();
        jtpModificar = new javax.swing.JTabbedPane();
        jpModificar = new javax.swing.JPanel();
        jlNombreCine = new javax.swing.JLabel();
        jlCifCine = new javax.swing.JLabel();
        jlIDBuscador = new javax.swing.JLabel();
        jlDireccionCine = new javax.swing.JLabel();
        jlPoblacionCine = new javax.swing.JLabel();
        jlCodigoPostal = new javax.swing.JLabel();
        jtfIDBuscador = new javax.swing.JTextField();
        jtfPeliculaModificar = new javax.swing.JTextField();
        jtfSesionModificar = new javax.swing.JTextField();
        jtfFilaModificar = new javax.swing.JTextField();
        jtfColumnaModificar = new javax.swing.JTextField();
        jtfDNIModificar = new javax.swing.JTextField();
        jbtModificar = new javax.swing.JButton();
        jbtBuscarReservaModificar = new javax.swing.JButton();
        jlNombreActual = new javax.swing.JLabel();
        jlDireccionActual = new javax.swing.JLabel();
        jlPoblacionActual = new javax.swing.JLabel();
        jlCodigoPostalActual = new javax.swing.JLabel();
        jlIDReservaResultado = new javax.swing.JLabel();
        jlDNIResultado = new javax.swing.JLabel();
        jlCodigoPostalActual1 = new javax.swing.JLabel();
        jlCodigoPostalActual2 = new javax.swing.JLabel();
        jlPeliculaResultado = new javax.swing.JLabel();
        jlSesionResultado = new javax.swing.JLabel();
        jlColumnaResultado = new javax.swing.JLabel();
        jlFilaResultado = new javax.swing.JLabel();
        jlCodigoPostalActual3 = new javax.swing.JLabel();
        jlNombreSalaResultado = new javax.swing.JLabel();
        jtpAltaCine = new javax.swing.JTabbedPane();
        jpAltaCine = new javax.swing.JPanel();
        jlNombre = new javax.swing.JLabel();
        jtfPeliculaAlta = new javax.swing.JTextField();
        jlCif = new javax.swing.JLabel();
        jtfHoraSesionAlta = new javax.swing.JTextField();
        jlDireccion = new javax.swing.JLabel();
        jtfFilaButacaAlta = new javax.swing.JTextField();
        jlPoblacion = new javax.swing.JLabel();
        jtfColumnaButacaAlta = new javax.swing.JTextField();
        jbAltaReserva = new javax.swing.JButton();
        jlPoblacion1 = new javax.swing.JLabel();
        jtfNombreSalaAlta = new javax.swing.JTextField();
        jlPoblacion2 = new javax.swing.JLabel();
        jtfDniClienteAlta = new javax.swing.JTextField();
        jtpEliminar = new javax.swing.JTabbedPane();
        jpFondoEleminar = new javax.swing.JPanel();
        jlCifCineEliminar = new javax.swing.JLabel();
        jtfIDReservaEliminar = new javax.swing.JTextField();
        jlCineAEliminar = new javax.swing.JLabel();
        jbAceptarCifEleiminar = new javax.swing.JButton();
        jlIDReservaEliminar = new javax.swing.JLabel();
        jbComfirmarEliminar = new javax.swing.JButton();
        jlIDReservaEliminar1 = new javax.swing.JLabel();
        jlHoraSesionEliminar = new javax.swing.JLabel();
        jlFilaButacaEliminar = new javax.swing.JLabel();
        jlDniClienteEliminar = new javax.swing.JLabel();
        jlColumnaButacaEliminar = new javax.swing.JLabel();
        jlNombrePeliculaEliminar = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        lbTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitulo.setText("Ingrese el ID de la reserva o pulse Aceptar para búsqueda completar:");

        jlCifConsulta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlCifConsulta.setText("ID:");

        jtaConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtaConsulta);

        jbAceptarConsulta.setText("Aceptar");
        jbAceptarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAceptarConsultaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpConsultaLayout = new javax.swing.GroupLayout(jpConsulta);
        jpConsulta.setLayout(jpConsultaLayout);
        jpConsultaLayout.setHorizontalGroup(
            jpConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 927, Short.MAX_VALUE)
                    .addComponent(lbTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpConsultaLayout.createSequentialGroup()
                        .addComponent(jlCifConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtfIDConsulta))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpConsultaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbAceptarConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jpConsultaLayout.setVerticalGroup(
            jpConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jpConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCifConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfIDConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbAceptarConsulta)
                .addContainerGap(189, Short.MAX_VALUE))
        );

        jtpConsulta.addTab("", jpConsulta);

        jtpFondo.addTab("Consulta", jtpConsulta);

        jlNombreCine.setText("Nombre Película:");

        jlCifCine.setText("Hora  Sesión:");

        jlIDBuscador.setText("Ingrese el ID de la reserva que desea modificar:");

        jlDireccionCine.setText("Fila Butaca:");

        jlPoblacionCine.setText("Columna Butaca:");

        jlCodigoPostal.setText("DNI Cliente");

        jbtModificar.setText("Modificar");
        jbtModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtModificarActionPerformed(evt);
            }
        });

        jbtBuscarReservaModificar.setText("Buscar");
        jbtBuscarReservaModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtBuscarReservaModificarActionPerformed(evt);
            }
        });

        jlNombreActual.setText("ID Reserva Actual:");

        jlDireccionActual.setText("Nombre Película:");

        jlPoblacionActual.setText("Hora Sesión:");

        jlCodigoPostalActual.setText("Fila Butaca:");

        jlCodigoPostalActual1.setText("Columna Butaca:");

        jlCodigoPostalActual2.setText("DNI Cliente:");

        jlCodigoPostalActual3.setText("Nombre Sala:");

        javax.swing.GroupLayout jpModificarLayout = new javax.swing.GroupLayout(jpModificar);
        jpModificar.setLayout(jpModificarLayout);
        jpModificarLayout.setHorizontalGroup(
            jpModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpModificarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jbtModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(202, 202, 202))
            .addGroup(jpModificarLayout.createSequentialGroup()
                .addGroup(jpModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jlIDReservaResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlNombreActual, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jpModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlDireccionActual, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlPeliculaResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jpModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpModificarLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jlPoblacionActual, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpModificarLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jlSesionResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jpModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlFilaResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlCodigoPostalActual, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jpModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlColumnaResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlCodigoPostalActual1, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jpModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlCodigoPostalActual2, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                    .addComponent(jlDNIResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jpModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlCodigoPostalActual3, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                    .addComponent(jlNombreSalaResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(92, 92, 92))
            .addGroup(jpModificarLayout.createSequentialGroup()
                .addGroup(jpModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpModificarLayout.createSequentialGroup()
                        .addGroup(jpModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlNombreCine, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlCifCine, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlDireccionCine, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlPoblacionCine, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jpModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfSesionModificar)
                            .addComponent(jtfPeliculaModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
                            .addComponent(jtfFilaModificar)
                            .addComponent(jtfColumnaModificar)))
                    .addGroup(jpModificarLayout.createSequentialGroup()
                        .addComponent(jlCodigoPostal, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtfDNIModificar))
                    .addGroup(jpModificarLayout.createSequentialGroup()
                        .addComponent(jlIDBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtfIDBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtBuscarReservaModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 364, Short.MAX_VALUE))
        );
        jpModificarLayout.setVerticalGroup(
            jpModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpModificarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlIDBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfIDBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtBuscarReservaModificar))
                .addGap(18, 18, 18)
                .addGroup(jpModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlCodigoPostalActual2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlCodigoPostalActual3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlNombreActual, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlDireccionActual, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlPoblacionActual, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlCodigoPostalActual, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlCodigoPostalActual1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jpModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlIDReservaResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlPeliculaResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlSesionResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlFilaResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlColumnaResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlDNIResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlNombreSalaResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jpModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNombreCine, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfPeliculaModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfSesionModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCifCine, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlDireccionCine, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfFilaModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfColumnaModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlPoblacionCine, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCodigoPostal, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfDNIModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtModificar)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jtpModificar.addTab("", jpModificar);

        jtpFondo.addTab("Modificar", jtpModificar);

        jlNombre.setText("Nombre Película:");

        jlCif.setText("Hora Sesión:");

        jlDireccion.setText("Fila Butaca:");

        jlPoblacion.setText("Columna Butaca:");

        jbAltaReserva.setText("Aceptar");
        jbAltaReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAltaReservaActionPerformed(evt);
            }
        });

        jlPoblacion1.setText("Nombre Sala:");

        jlPoblacion2.setText("DNI Cliente:");

        javax.swing.GroupLayout jpAltaCineLayout = new javax.swing.GroupLayout(jpAltaCine);
        jpAltaCine.setLayout(jpAltaCineLayout);
        jpAltaCineLayout.setHorizontalGroup(
            jpAltaCineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAltaCineLayout.createSequentialGroup()
                .addGroup(jpAltaCineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpAltaCineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpAltaCineLayout.createSequentialGroup()
                            .addComponent(jlNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jtfPeliculaAlta))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpAltaCineLayout.createSequentialGroup()
                            .addComponent(jlCif, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jtfHoraSesionAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpAltaCineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jbAltaReserva)
                        .addGroup(jpAltaCineLayout.createSequentialGroup()
                            .addGroup(jpAltaCineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jlPoblacion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                                .addComponent(jlDireccion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jlPoblacion1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                                .addComponent(jlPoblacion2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE))
                            .addGap(18, 18, 18)
                            .addGroup(jpAltaCineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jtfColumnaButacaAlta, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                                .addComponent(jtfFilaButacaAlta)
                                .addComponent(jtfNombreSalaAlta, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                                .addComponent(jtfDniClienteAlta, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE))
                            .addGap(145, 145, 145))))
                .addContainerGap(268, Short.MAX_VALUE))
        );
        jpAltaCineLayout.setVerticalGroup(
            jpAltaCineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAltaCineLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpAltaCineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfPeliculaAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpAltaCineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCif, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfHoraSesionAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpAltaCineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfFilaButacaAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpAltaCineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlPoblacion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfColumnaButacaAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpAltaCineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfNombreSalaAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlPoblacion1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpAltaCineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfDniClienteAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlPoblacion2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(136, 136, 136)
                .addComponent(jbAltaReserva)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtpAltaCine.addTab("", jpAltaCine);

        jtpFondo.addTab("Alta", jtpAltaCine);

        jlCifCineEliminar.setText("Ingrese el ID de la reserva que desee eliminar:");

        jlCineAEliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlCineAEliminar.setText("Va a eliminar la siguiente reserva:");

        jbAceptarCifEleiminar.setText("Aceptar");
        jbAceptarCifEleiminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAceptarCifEleiminarActionPerformed(evt);
            }
        });

        jbComfirmarEliminar.setText("Eliminar");
        jbComfirmarEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbComfirmarEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpFondoEleminarLayout = new javax.swing.GroupLayout(jpFondoEleminar);
        jpFondoEleminar.setLayout(jpFondoEleminarLayout);
        jpFondoEleminarLayout.setHorizontalGroup(
            jpFondoEleminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFondoEleminarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpFondoEleminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpFondoEleminarLayout.createSequentialGroup()
                        .addComponent(jlCifCineEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtfIDReservaEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbAceptarCifEleiminar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jpFondoEleminarLayout.createSequentialGroup()
                        .addGroup(jpFondoEleminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jpFondoEleminarLayout.createSequentialGroup()
                                .addComponent(jlIDReservaEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jpFondoEleminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlIDReservaEliminar1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jpFondoEleminarLayout.createSequentialGroup()
                                        .addComponent(jlNombrePeliculaEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jlHoraSesionEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jlFilaButacaEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jlCineAEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jpFondoEleminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpFondoEleminarLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jbComfirmarEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpFondoEleminarLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                                .addComponent(jlColumnaButacaEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jlDniClienteEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(75, 75, 75))))))
        );
        jpFondoEleminarLayout.setVerticalGroup(
            jpFondoEleminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFondoEleminarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpFondoEleminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpFondoEleminarLayout.createSequentialGroup()
                        .addGroup(jpFondoEleminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpFondoEleminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jtfIDReservaEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jlCifCineEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpFondoEleminarLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jbAceptarCifEleiminar)))
                        .addGap(18, 18, 18)
                        .addComponent(jlCineAEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jlIDReservaEliminar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpFondoEleminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlNombrePeliculaEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpFondoEleminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jlIDReservaEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlHoraSesionEliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jlFilaButacaEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlColumnaButacaEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlDniClienteEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jbComfirmarEliminar)
                .addContainerGap())
        );

        jtpEliminar.addTab("", jpFondoEleminar);

        jtpFondo.addTab("Eliminar", jtpEliminar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtpFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 957, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtpFondo)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbAceptarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAceptarConsultaActionPerformed
        consultaReserva();
    }//GEN-LAST:event_jbAceptarConsultaActionPerformed

    private void jbtBuscarReservaModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtBuscarReservaModificarActionPerformed
        cargarReservaModificar();
    }//GEN-LAST:event_jbtBuscarReservaModificarActionPerformed

    private void jbAltaReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAltaReservaActionPerformed
        insertarReserva();
    }//GEN-LAST:event_jbAltaReservaActionPerformed

    private void jbComfirmarEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbComfirmarEliminarActionPerformed
        eliminarReserva();
    }//GEN-LAST:event_jbComfirmarEliminarActionPerformed

    private void jbAceptarCifEleiminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAceptarCifEleiminarActionPerformed
        cargarReservaEliminar();
    }//GEN-LAST:event_jbAceptarCifEleiminarActionPerformed

    private void jbtModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtModificarActionPerformed
        modificarReserva();
    }//GEN-LAST:event_jbtModificarActionPerformed

    
    /**
     * Método usado para limpiar las tablas de cara a una nueva consulta.
     */
    private void limpiarTabla() {
        jtaConsulta.setModel(dtm);
        dtm.setRowCount(0);
    }
    
public void consultaReserva() {
        String idBuscador = jtfIDConsulta.getText();

        if (idBuscador.equals("")) {
            /* Búsqueda general de proveedores. */
            try {
                alReserva = rp.listarReservas();
                dtm.setRowCount(alReserva.size());
                for (int i = 0; i < alReserva.size(); i++) {
                    jtaConsulta.setValueAt(alReserva.get(i).getId_reserva(), i, 0);
                    String nombrePelicula = rp.buscarNombrePelicula(alReserva.get(i).getId_pelicula());
                    jtaConsulta.setValueAt(nombrePelicula, i, 1);
                    Time hora = rp.consultarHoraSesion(alReserva.get(i).getId_sesion());
                    jtaConsulta.setValueAt(String.valueOf(hora), i, 2);
                    int fila = rp.consultarFilaButaca(alReserva.get(i).getId_butaca());
                    int columna = rp.consultarColumnaButaca(alReserva.get(i).getId_butaca());
                    jtaConsulta.setValueAt(String.valueOf(fila), i, 3);
                    jtaConsulta.setValueAt(String.valueOf(columna), i, 4);
                    String dni = rp.consultarDniCliente(alReserva.get(i).getId_cliente());
                    jtaConsulta.setValueAt(dni, i, 5);
                }
            } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(null, "Error en la aplicación.\nNo se ha podido consultar ninguna reserva.\nPruebe de nuevo.");
                ex.printStackTrace();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "El ID NO EXISTE.");
                ex.printStackTrace();
            }
        } else {
            /* Búsqueda específica de proveedor por CIF. */
            try {

                int idBuscar = Integer.parseInt(idBuscador);
                reserva = rp.buscarReserva(idBuscar);
                dtm.setRowCount(1);
                jtaConsulta.setValueAt(reserva.getId_reserva(), 0, 0);
                String nombrePelicula = rp.buscarNombrePelicula(reserva.getId_pelicula());
                jtaConsulta.setValueAt(nombrePelicula, 0, 1);
                Time hora = rp.consultarHoraSesion(reserva.getId_sesion());
                jtaConsulta.setValueAt(String.valueOf(hora), 0, 2);
                int fila = rp.consultarFilaButaca(reserva.getId_butaca());
                int columna = rp.consultarColumnaButaca(reserva.getId_butaca());
                jtaConsulta.setValueAt(String.valueOf(fila), 0, 3);
                jtaConsulta.setValueAt(String.valueOf(columna), 0, 4);
                String dni = rp.consultarDniCliente(reserva.getId_cliente());
                jtaConsulta.setValueAt(dni, 0, 5);

            } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(null, "Error en la aplicación.\nNo se ha podido consultar la reserva solicitada.\nPruebe de nuevo.");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "El ID NO EXISTE.");
                ex.printStackTrace();
            }
        }
    }

    public void insertarReserva(){
        try {
            int idPelicula = rp.consultarIdPelicula(jtfPeliculaAlta.getText());
            int fila = Integer.parseInt(jtfFilaButacaAlta.getText());
            int columna = Integer.parseInt(jtfColumnaButacaAlta.getText());
            DateFormat format = new SimpleDateFormat("HH:mm:ss");
            Date horaSesion = (Date)format.parse(jtfHoraSesionAlta.getText());
            DateFormat dsf = new SimpleDateFormat("HH:mm:ss");
            String timeFormat = dsf.format(horaSesion);
            java.sql.Time hora = java.sql.Time.valueOf(timeFormat); 
            String nombreSala = jtfNombreSalaAlta.getText();
            String dniCliente = jtfDniClienteAlta.getText();
            int idSala = rp.consultarIDSala(nombreSala);
            System.out.println("Sala: "+ idSala +"fila: "+fila + "columna: " + columna + "hora: " + hora.toString());
            int idButaca = rp.consultarIDButaca(fila, columna, idSala);
            int idSesion = rp.consultarIDSesion(hora, idPelicula, idSala);
            int idCliente = rp.consultaIdCliente(dniCliente);
            reserva = new Reserva(idPelicula, idSesion, idButaca, idCliente);
            rp.ingresarReserva(reserva);
            reiniciarCamposAlta();
            JOptionPane.showMessageDialog(null, "Reserva ingresada con éxito.");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error de conexión con la BD.\nNo se ha podido ingresar la nueva butaca.\nPruebe de nuevo." + ex);
            ex.printStackTrace();
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Error en la aplicación.\nPruebe de nuevo.");
        } catch (ParseException ex) {
            Logger.getLogger(JIFGestionReservas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void cargarReservaModificar() {
        String idBuscador = jtfIDBuscador.getText();
        boolean existe = false;
        if (idBuscador.compareToIgnoreCase("") == 0) {
            JOptionPane.showMessageDialog(null, "Ingrese un ID válido.");
        } else {
            try {
                int idReserva = Integer.parseInt(idBuscador);
                existe = rp.existeReserva(idReserva);
                if (existe) {
                    reserva = rp.buscarReserva(idReserva);
                    Integer idPelicula = reserva.getId_pelicula();
                    Integer idSesion = reserva.getId_sesion();
                    Integer idButaca = reserva.getId_butaca();
                    Integer idCliente = reserva.getId_cliente();
                    
                    String nombrePelicula = rp.buscarNombrePelicula(idPelicula);
                    int fila = rp.consultarFilaButaca(idButaca);
                    int columna = rp.consultarColumnaButaca(idButaca);
                    Time horaSesion = rp.consultarHoraSesion(idSesion);
                    String dniCliente = rp.consultarDniCliente(idCliente);
                    
                    jlFilaResultado.setText(String.valueOf(fila));
                    jlColumnaResultado.setText(String.valueOf(columna));
                    jlSesionResultado.setText(horaSesion.toString());
                    jlPeliculaResultado.setText(nombrePelicula);
                    jlDNIResultado.setText(dniCliente);
                    jlIDReservaResultado.setText(String.valueOf(idReserva));
                    jlNombreSalaResultado.setText(rp.consultarNombreSala(nombrePelicula));
                    
                    jtfPeliculaModificar.setText(nombrePelicula);
                    jtfFilaModificar.setText(String.valueOf(fila));
                    jtfColumnaModificar.setText(String.valueOf(columna));
                    jtfSesionModificar.setText(horaSesion.toString());
                    jtfDNIModificar.setText(dniCliente);
                    
                    jbtModificar.setEnabled(true);
                } else {
                    JOptionPane.showMessageDialog(null, "No existe la butaca con el ID seleccionado.\nPruebe de nuevo." );
                    jtfIDBuscador.setText("");
                }
            } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(null, "Error en la aplicación.\nNo se ha podido consultar la butaca solicitado.\nPruebe de nuevo." +ex);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error de conexión con la BD.\nPruebe de nuevo." +ex);
            }
        }
    }
    
    public void modificarReserva() {
        try {
            int idReserva = Integer.parseInt(jtfIDBuscador.getText());
            //Falta coger el cine
            int fila = Integer.parseInt(jtfFilaModificar.getText());
            int columna = Integer.parseInt(jtfColumnaModificar.getText());
            String dni = jtfDNIModificar.getText();
            String pelicula = jtfPeliculaModificar.getText();
            DateFormat format = new SimpleDateFormat("HH:mm:ss");
            Date horaSesion = (Date)format.parse(jtfSesionModificar.getText());
            DateFormat dsf = new SimpleDateFormat("HH:mm:ss");
            String timeFormat = dsf.format(horaSesion);
            java.sql.Time hora = java.sql.Time.valueOf(timeFormat);
            String nombreSala = jlNombreSalaResultado.getText();
            int idSala = rp.consultarIDSala(nombreSala);
            int idPelicula = rp.consultarIDPelicula(pelicula, idSala);
            int idSesion = rp.consultarIDSesion(hora, idPelicula, idSala);
            int idButaca = rp.consultarIDButaca(fila, columna, idSala);
            int idCliente = rp.consultaIdCliente(dni);
            reserva = new Reserva(idPelicula, idSesion, idButaca, idCliente);
            rp.actualizarReserva(reserva, idReserva);
            reiniciarCamposModificar();
            JOptionPane.showMessageDialog(null, "Reserva actualizada con éxito.");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error de conexión con la BD.\nPruebe de nuevo." + ex);
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Error en la aplicación.\nNo se ha podido modificar la reserva solicitado.\nPruebe de nuevo.");
        } catch (ParseException ex) {
            Logger.getLogger(JIFGestionReservas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void cargarReservaEliminar() {
        String idBusca = jtfIDReservaEliminar.getText();

        if (idBusca.compareToIgnoreCase("") == 0) {
            JOptionPane.showMessageDialog(null, "Ingrese un ID válido.");
        } else {
            try {
                int idReserva = Integer.parseInt(idBusca);
                reserva = rp.buscarReserva(idReserva);
                 Integer idPelicula = reserva.getId_pelicula();
                    Integer idSesion = reserva.getId_sesion();
                    Integer idButaca = reserva.getId_butaca();
                    Integer idCliente = reserva.getId_cliente();
                    
                    String nombrePelicula = rp.buscarNombrePelicula(idPelicula);
                    int fila = rp.consultarFilaButaca(idButaca);
                    int columna = rp.consultarColumnaButaca(idButaca);
                    Time horaSesion = rp.consultarHoraSesion(idSesion);
                    String dniCliente = rp.consultarDniCliente(idCliente);
                    
                    jlFilaButacaEliminar.setText("Fila: " + String.valueOf(fila));
                    jlColumnaButacaEliminar.setText("Columna: " + String.valueOf(columna));
                    jlHoraSesionEliminar.setText("Hora: " + horaSesion.toString());
                    jlNombrePeliculaEliminar.setText("Pelicula: " + nombrePelicula);
                    jlDniClienteEliminar.setText("DNI: " + dniCliente);
                    jlIDReservaEliminar.setText("ID Reserva: " + String.valueOf(idReserva));
                    
                    jbComfirmarEliminar.setEnabled(true);
            } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(null, "Error en la aplicación.\nNo se ha podido consultar la reserva solicitado.\nPruebe de nuevo.");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Error de conexión con la BD.\nPruebe de nuevo.");
            }
        }
    }
     
    public void eliminarReserva(){
        String idEliminar = jtfIDReservaEliminar.getText();
        try {
            int id = Integer.parseInt(idEliminar);
            rp.eliminarReserva(id);
            reiniciarCamposEliminar();
            JOptionPane.showMessageDialog(null, "Reserva eliminada con éxito.");
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Error en la aplicación.\nNo se ha podido eliminar la reserva solicitada.\nPruebe de nuevo.");
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error de conexión con la BD.\nPruebe de nuevo.");
        }
    }
    
    
    
    /**
     * Método usado para reiniciar los campos de la ventana Consulta cuando se
     * produce un cambio de ventana.
     */
    public void reiniciarCamposConsulta() {
        jtfIDConsulta.setText("");
        for (int i = 0; i < jtaConsulta.getRowCount(); i++) {
            dtm.removeRow(i);
            i -= 1;
        }
    }

    /**
     * Método usado para reiniciar los campos de la ventana Modificar cuando se
     * produce un cambio de ventana.
     */
    public void reiniciarCamposModificar() {
        jtfIDBuscador.setText("");
        jtfPeliculaModificar.setText("");
        jtfSesionModificar.setText("");
        jtfFilaModificar.setText("");
        jtfColumnaModificar.setText("");
        jtfDNIModificar.setText("");
        
        jlIDReservaResultado.setText("");
        jlPeliculaResultado.setText("");
        jlSesionResultado.setText("");
        jlFilaResultado.setText("");
        jlColumnaResultado.setText("");
        jlNombreSalaResultado.setText("");
        jbtModificar.setEnabled(false);
    }

    /**
     * Método usado para reiniciar los campos de la ventana Alta cuando se
     * produce un cambio de ventana.
     */
    public void reiniciarCamposAlta() {
        jtfPeliculaAlta.setText("");
        jtfHoraSesionAlta.setText("");
        jtfFilaButacaAlta.setText("");
        jtfColumnaButacaAlta.setText("");
        jtfNombreSalaAlta.setText("");
        jtfDniClienteAlta.setText("");
    }

    /**
     * Método usado para reiniciar los campos de la ventana Eliminar cuando se
     * produce un cambio de ventana.
     */
    public void reiniciarCamposEliminar() {
        jtfIDReservaEliminar.setText("");
        jlIDReservaEliminar.setText("");
        jlHoraSesionEliminar.setText("");
        jlFilaButacaEliminar.setText("");
        jlColumnaButacaEliminar.setText("");
        jlDniClienteEliminar.setText("");
        jlNombrePeliculaEliminar.setText("");
        jbComfirmarEliminar.setEnabled(false);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAceptarCifEleiminar;
    private javax.swing.JButton jbAceptarConsulta;
    private javax.swing.JButton jbAltaReserva;
    private javax.swing.JButton jbComfirmarEliminar;
    private javax.swing.JButton jbtBuscarReservaModificar;
    private javax.swing.JButton jbtModificar;
    private javax.swing.JLabel jlCif;
    private javax.swing.JLabel jlCifCine;
    private javax.swing.JLabel jlCifCineEliminar;
    private javax.swing.JLabel jlCifConsulta;
    private javax.swing.JLabel jlCineAEliminar;
    private javax.swing.JLabel jlCodigoPostal;
    private javax.swing.JLabel jlCodigoPostalActual;
    private javax.swing.JLabel jlCodigoPostalActual1;
    private javax.swing.JLabel jlCodigoPostalActual2;
    private javax.swing.JLabel jlCodigoPostalActual3;
    private javax.swing.JLabel jlColumnaButacaEliminar;
    private javax.swing.JLabel jlColumnaResultado;
    private javax.swing.JLabel jlDNIResultado;
    private javax.swing.JLabel jlDireccion;
    private javax.swing.JLabel jlDireccionActual;
    private javax.swing.JLabel jlDireccionCine;
    private javax.swing.JLabel jlDniClienteEliminar;
    private javax.swing.JLabel jlFilaButacaEliminar;
    private javax.swing.JLabel jlFilaResultado;
    private javax.swing.JLabel jlHoraSesionEliminar;
    private javax.swing.JLabel jlIDBuscador;
    private javax.swing.JLabel jlIDReservaEliminar;
    private javax.swing.JLabel jlIDReservaEliminar1;
    private javax.swing.JLabel jlIDReservaResultado;
    private javax.swing.JLabel jlNombre;
    private javax.swing.JLabel jlNombreActual;
    private javax.swing.JLabel jlNombreCine;
    private javax.swing.JLabel jlNombrePeliculaEliminar;
    private javax.swing.JLabel jlNombreSalaResultado;
    private javax.swing.JLabel jlPeliculaResultado;
    private javax.swing.JLabel jlPoblacion;
    private javax.swing.JLabel jlPoblacion1;
    private javax.swing.JLabel jlPoblacion2;
    private javax.swing.JLabel jlPoblacionActual;
    private javax.swing.JLabel jlPoblacionCine;
    private javax.swing.JLabel jlSesionResultado;
    private javax.swing.JPanel jpAltaCine;
    private javax.swing.JPanel jpConsulta;
    private javax.swing.JPanel jpFondoEleminar;
    private javax.swing.JPanel jpModificar;
    private javax.swing.JTable jtaConsulta;
    private javax.swing.JTextField jtfColumnaButacaAlta;
    private javax.swing.JTextField jtfColumnaModificar;
    private javax.swing.JTextField jtfDNIModificar;
    private javax.swing.JTextField jtfDniClienteAlta;
    private javax.swing.JTextField jtfFilaButacaAlta;
    private javax.swing.JTextField jtfFilaModificar;
    private javax.swing.JTextField jtfHoraSesionAlta;
    private javax.swing.JTextField jtfIDBuscador;
    private javax.swing.JTextField jtfIDConsulta;
    private javax.swing.JTextField jtfIDReservaEliminar;
    private javax.swing.JTextField jtfNombreSalaAlta;
    private javax.swing.JTextField jtfPeliculaAlta;
    private javax.swing.JTextField jtfPeliculaModificar;
    private javax.swing.JTextField jtfSesionModificar;
    private javax.swing.JTabbedPane jtpAltaCine;
    private javax.swing.JTabbedPane jtpConsulta;
    private javax.swing.JTabbedPane jtpEliminar;
    private javax.swing.JTabbedPane jtpFondo;
    private javax.swing.JTabbedPane jtpModificar;
    private javax.swing.JLabel lbTitulo;
    // End of variables declaration//GEN-END:variables
}
